// @generated by protobuf-ts 2.9.0 with parameter server_generic
// @generated from protobuf file "time.proto" (package "time", syntax proto3)
// tslint:disable
import { TimeResponse } from "./time";
import { TimeRequest } from "./time";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service time.TimeRoutes
 */
export interface ITimeRoutes<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: request(time.TimeRequest) returns (time.TimeResponse);
     */
    request(request: TimeRequest, context: T): Promise<TimeResponse>;
}
